### ISSUE TITLE
What are mapgen->map->roads for?

### ISSUE THREAD

**Issue by spacehamster** [averrin/libmapgen#6]
```mapgen->map->roads``` seems to connect all locations to each other
![roads](https://user-images.githubusercontent.com/3821056/42731388-ab868c48-884f-11e8-9811-d4c014aa1f78.png)
while ```mapgen->map->roadMap``` connects nearby locations
![locationroads](https://user-images.githubusercontent.com/3821056/42731389-ae99005a-884f-11e8-894f-fa346cf4d6c2.png)

is roads just used for internal temporary values, or is it part of the simulation or some future functionality?

**Comment by averrin** [comment]
`roadMap` is newer (https://github.com/averrin/libmapgen/commit/5ce31b24e0e5e2bed441f6f3fd03b57c842f77b2) and better for display but maybe `roads` still needs for simulation.

I see awesome results in unity. Can you explain how you use my lib and what you want make with it? I very proud to see this screenshots.

**Comment by spacehamster** [comment]
I'm trying to create a open world turn based rpg, its really early stage. I'd use mapgen to create the large scale world, and fill it with cities and dungeons etc. I like the way the landmasses end up looking.

**Comment by averrin** [comment]
You use mapgen as Unity Native Plugin with your own facade? There is interesting magic if you need recompile .dll file: http://runningdimensions.com/blog/?p=5
